import { useEffect, useRef, useState } from "react";
import { useCreateUOM } from "@/api/uom/uom.mutation";
import { UOM } from "@/api/uom/uom.types";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { TextInput } from "@/components/reusable/partials/input";
import Loading from "@/components/reusable/partials/loading";
import { AxiosError } from "axios";
import { CreateUOMValidationErrors } from "@/api/uom/uom.types";

interface QuickCreateUomModalProps {
  open: boolean;
  onClose: () => void;
  /** Pre-linked base unit. Category will be inherited from it. */
  baseUnit: UOM;
  /** Called with the newly created UOM so the parent can select it */
  onCreated: (uom: UOM) => void;
}

export function QuickCreateUomModal({
  open,
  onClose,
  baseUnit,
  onCreated,
}: QuickCreateUomModalProps) {
  const nameRef = useRef<HTMLInputElement>(null);
  const mutation = useCreateUOM();
  const fieldErrors = (mutation.error as AxiosError<CreateUOMValidationErrors> | null)
    ?.response?.data?.errors;

  const [form, setForm] = useState({
    name: "",
    symbol: "",
    conversion_factor: "",
  });

  // Reset form & focus when modal opens
  useEffect(() => {
    if (open) {
      setForm({ name: "", symbol: "", conversion_factor: "" });
      setTimeout(() => nameRef.current?.focus(), 80);
    }
  }, [open]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    setForm(prev => ({ ...prev, [id]: value }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    mutation.mutate(
      {
        name: form.name,
        symbol: form.symbol || undefined,
        conversion_factor: parseFloat(form.conversion_factor) || 1,
        is_base_unit: false,
        base_uom_id: baseUnit.id,
        category_id: baseUnit.category_id,
        is_active: true,
      },
      {
        onSuccess: res => {
          onCreated(res.data);
          onClose();
        },
      }
    );
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Quick Create Unit</DialogTitle>
        </DialogHeader>

        <p className="text-sm text-muted-foreground -mt-2 mb-2">
          Creating a derived unit under{" "}
          <span className="font-medium text-foreground">{baseUnit.name}</span>
          {baseUnit.category && (
            <> &mdash; category: <span className="font-medium text-foreground">{baseUnit.category.name}</span></>
          )}
        </p>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <TextInput
                id="name"
                label="Unit Name"
                placeholder="e.g., Blister Pack"
                value={form.name}
                error={fieldErrors?.name?.[0]}
                required
                onChange={handleChange}
              />
            </div>
            {/* Code auto-generated by backend — no input needed */}
            <TextInput
              id="symbol"
              label="Symbol"
              placeholder="e.g., bls"
              value={form.symbol}
              error={fieldErrors?.symbol?.[0]}
              onChange={handleChange}
            />
          </div>

          <div>
            <TextInput
              id="conversion_factor"
              type="number"
              label="Conversion Factor"
              placeholder={`How many ${baseUnit.name} equal 1 of this unit?`}
              value={form.conversion_factor}
              error={fieldErrors?.conversion_factor?.[0]}
              required
              onChange={handleChange}
            />
            <p className="mt-1 text-xs text-muted-foreground">
              Defines how many <strong>{baseUnit.name}</strong> are contained in
              one of this new unit.
            </p>
          </div>

          <div className="flex justify-end gap-3 pt-2 border-t">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button
              type="submit"
              className="bg-[#5c52d6] hover:bg-[#4b43b3] text-white"
              disabled={mutation.isPending}
            >
              {mutation.isPending ? <Loading /> : "Create & Select"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
